apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-store-sample-app-catalog-mysql
  namespace: retail-app
  labels:
    app.kubernetes.io/name: retail-store-sample-app-catalog-mysql
    app.kubernetes.io/component: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: retail-store-sample-app-catalog-mysql
  template:
    metadata:
      labels:
        app.kubernetes.io/name: retail-store-sample-app-catalog-mysql
    spec:
      containers:
      - name: mysql
        # CHANGED: Use the official standard MySQL image
        image: mysql:5.7
        env:
        - name: MYSQL_DATABASE
          value: "catalog"
        - name: MYSQL_USER
          value: "catalog"
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: catalog-db-secret
              key: password
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: catalog-db-secret
              key: password
        ports:
        - containerPort: 3306
          name: mysql
